[project]
name = "task-manager"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.1",
]

[dependency-groups]
dev = [
    "ruff>=0.11.12",
]
